import { NarrativeTopic, ChainMapping, DebateResult } from '../../models/types';

export class SynthesisAgent {
  /**
   * Generates the final Daily Brief Markdown report combining mapping and debate findings
   */
  generateDailyBrief(topic: NarrativeTopic, mapping: ChainMapping, debate: DebateResult): string {
    console.log(`\n[SynthesisAgent] 📝 Synthesizing Executive Daily Brief...`);

    const date = new Date().toISOString().split('T')[0];
    let markdown = `# 📈 OpenClaw Daily Executive Brief: ${date}\n\n`;
    
    markdown += `## 🎯 Top Narrative Profile: **${topic.title}**\n`;
    markdown += `> **Impact Score:** \`${topic.impactScore}/100\`\n\n`;
    markdown += `**Overview:** ${topic.description}\n\n`;

    markdown += `## 🚨 铁血风控与证伪条件 (Ironclad Invalidation Stops)\n`;
    if (debate.ironcladStopLosses && debate.ironcladStopLosses.length > 0) {
      debate.ironcladStopLosses.forEach(b => markdown += `> **❌ 警告:** ${b}\n`);
    } else {
      markdown += `> 未提取到明确止损条件，交易极度危险！\n`;
    }
    markdown += `\n`;

    markdown += `## 🗺️ 产业链推导与标的映射 (Supply Chain Deduction)\n`;
    markdown += `*   **🔥 顶层事件 / 核心龙头:** \`${mapping.coreTickers.join('\`, \`') || 'None'}\`\n`;
    markdown += `*   **👀 同步验证辅标的:** \`${mapping.confirmTickers.join('\`, \`') || 'None'}\`\n`;
    markdown += `*   **🎯 重点埋伏次级滞涨标的 (跟随套利):** \`${mapping.mappingTickers.join('\`, \`') || 'None'}\`\n`;
    markdown += `\n**👇 严密推导链条 (Deduction Chain):**\n`;
    if (mapping.deductionChain) {
        mapping.deductionChain.forEach((step, idx) => markdown += `${idx + 1}. ${step}\n`);
    }
    markdown += `\n> **总括宏观逻辑:** ${mapping.logicDescription}\n\n`;

    markdown += `## ⚔️ 多方视角提纯 (Multi-Angle Intelligence Assembly)\n`;
    markdown += `### 🐂 多头爆发核心点 (Bull Catalyst)\n${debate.bullCaseSummary}\n\n`;
    markdown += `**向上突破引爆剂 (Key Triggers):**\n`;
    debate.keyTriggers.forEach(t => markdown += `- ${t}\n`);

    markdown += `\n### 🐻 审慎反向防御 (Bear Defense)\n${debate.bearCaseSummary}\n\n`;

    markdown += `\n---\n*Generated by OpenClaw Autonomous Intelligence Desk*`;

    return markdown;
  }
}
