import { NarrativeTopic, ChainMapping, DebateResult } from '../../models/types';

export class SynthesisAgent {
  /**
   * Generates the final Daily Brief Markdown report combining mapping and debate findings
   */
  generateDailyBrief(topic: NarrativeTopic, mapping: ChainMapping, debate: DebateResult): string {
    console.log(`\n[SynthesisAgent] 📝 Synthesizing Executive Daily Brief...`);

    const date = new Date().toISOString().split('T')[0];
    let markdown = `# 📈 OpenClaw Daily Executive Brief: ${date}\n\n`;
    
    markdown += `## 🎯 Top Narrative Profile: **${topic.title}**\n`;
    markdown += `> **Lifecycle Stage:** \`${topic.stage}\` | **Impact Score:** \`${topic.impactScore}/100\`\n\n`;
    markdown += `**Overview:** ${topic.description}\n\n`;

    markdown += `## 🗺️ Chain Mapping (Actionable Targets)\n`;
    markdown += `*   **Core Beneficiaries:** \`${mapping.coreTickers.join('\`, \`') || 'None configured'}\`\n`;
    markdown += `*   **Confirm Tickers:** \`${mapping.confirmTickers.join('\`, \`') || 'None configured'}\`\n`;
    markdown += `*   **Mapping/Derivative Options:** \`${mapping.mappingTickers.join('\`, \`') || 'None configured'}\`\n`;
    markdown += `> **Logic Overview:** ${mapping.logicDescription}\n\n`;

    markdown += `## ⚔️ Bull vs Bear Clash Judgment\n`;
    markdown += `**🟢 Bull Case Probability:** ${debate.bullProbability}%\n\n`;
    markdown += `### 🐂 The Bull Case\n${debate.bullCaseSummary}\n\n`;
    markdown += `**Key Upward Triggers:**\n`;
    debate.keyTriggers.forEach(t => markdown += `- ${t}\n`);

    markdown += `\n### 🐻 The Bear Case\n${debate.bearCaseSummary}\n\n`;
    markdown += `**Bear Invalidation / Stop Loss:**\n`;
    debate.bearInvalidation.forEach(b => markdown += `- ${b}\n`);

    markdown += `\n---\n*Generated by OpenClaw Autonomous Intelligence Desk*`;

    return markdown;
  }
}
