import { NarrativeTopic, ChainMapping, DebateResult } from '../../models/types';

export class SynthesisAgent {
  /**
   * Generates the final Daily Brief Markdown report
   * 报告结构: 止损 → 产业链 → 多空辩论 → (宏观附录) → (绩效追踪)
   */
  generateDailyBrief(
    topic: NarrativeTopic,
    mapping: ChainMapping,
    debate: DebateResult,
    macroAppendix?: string,
    performanceAppendix?: string,
  ): string {
    console.log(`\n[SynthesisAgent] 📝 Synthesizing Executive Daily Brief...`);

    const date = new Date().toISOString().split('T')[0];
    let markdown = `# 📈 OpenClaw 深度研报: ${date}\n\n`;
    
    // ====== 第一屏：叙事概览 ======
    markdown += `## 🎯 叙事主题: **${topic.title}**\n`;
    markdown += `> **冲击力评分:** \`${topic.impactScore}/100\`\n\n`;
    markdown += `**概述:** ${topic.description}\n\n`;

    // ====== 第二屏：风控（最重要，置顶）======
    markdown += `## 🚨 铁血风控与证伪条件\n`;
    if (debate.ironcladStopLosses && debate.ironcladStopLosses.length > 0) {
      debate.ironcladStopLosses.forEach(b => markdown += `> **❌ 警告:** ${b}\n`);
    } else {
      markdown += `> 未提取到明确止损条件，交易极度危险！\n`;
    }
    markdown += `\n`;

    // ====== 第三屏：产业链推导与标的映射 ======
    markdown += `## 🗺️ 产业链推导与标的映射\n`;
    markdown += `*   **👑 赛道龙头:** \`${mapping.coreTickers.join('\`, \`') || 'None'}\`\n`;
    markdown += `*   **🔍 瓶颈验证:** \`${mapping.confirmTickers.join('\`, \`') || 'None'}\`\n`;
    markdown += `*   **🎯 洼地埋伏:** \`${mapping.mappingTickers.join('\`, \`') || 'None'}\`\n`;
    markdown += `\n**👇 推导链条:**\n`;
    if (mapping.deductionChain) {
        mapping.deductionChain.forEach((step, idx) => markdown += `${idx + 1}. ${step}\n`);
    }
    markdown += `\n> **总括逻辑:** ${mapping.logicDescription}\n\n`;

    // ====== 第四屏：多空辩论 ======
    markdown += `## ⚔️ 多空辩论\n`;
    markdown += `### 🐂 多头核心论据\n${debate.bullCaseSummary}\n\n`;
    markdown += `**向上突破催化:**\n`;
    debate.keyTriggers.forEach(t => markdown += `- ${t}\n`);
    markdown += `\n### 🐻 空方核心论据\n${debate.bearCaseSummary}\n\n`;

    // ====== 附录：宏观 + 地缘（仅展示） ======
    if (macroAppendix) {
      markdown += `\n---\n\n${macroAppendix}\n`;
    }

    // ====== 附录：历史推荐绩效 ======
    if (performanceAppendix) {
      markdown += `\n---\n\n${performanceAppendix}\n`;
    }

    markdown += `\n---\n*Generated by OpenClaw Autonomous Intelligence Desk*`;

    return markdown;
  }
}

